version: "3.0"

services:
  api:
    container_name: "api"
    volumes:
      - ./app:/app
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 8080:8080
    tty: true
    stdin_open: true